//This file is automatically generated, modifications will be lost!
#define CC_CONTAINER_DECLARE_PRESET_CCArray() \
CC_CONTAINER_DECLARE(CCArray, CCChar); \
CC_CONTAINER_DECLARE(CCArray, CCFontGlyph); \
CC_CONTAINER_DECLARE(CCArray, CC_CONTAINER(CCLinkedList, HKHubArchExecutionGraphInstruction)); \
CC_CONTAINER_DECLARE(CCArray, HKHubArchAssemblyASTType); \
CC_CONTAINER_DECLARE(CCArray, HKHubArchExecutionGraphRange); \
CC_CONTAINER_DECLARE(CCArray, HKHubArchJITBlock); \
CC_CONTAINER_DECLARE(CCArray, HKHubArchJITBlockRelativeEntry); \
CC_CONTAINER_DECLARE(CCArray, uint8_t);

#define CC_CONTAINER_DECLARE_PRESET_CCCollection() \
CC_CONTAINER_DECLARE(CCCollection, CCCollectionEntry); \
CC_CONTAINER_DECLARE(CCCollection, CCComponent); \
CC_CONTAINER_DECLARE(CCCollection, CCEntity); \
CC_CONTAINER_DECLARE(CCCollection, CCString); \
CC_CONTAINER_DECLARE(CCCollection, FSPath); \
CC_CONTAINER_DECLARE(CCCollection, GFXDrawInputBuffer); \
CC_CONTAINER_DECLARE(CCCollection, GFXDrawInputTexture); \
CC_CONTAINER_DECLARE(CCCollection, GFXDrawInputVertexBuffer); \
CC_CONTAINER_DECLARE(CCCollection, GUIObject); \
CC_CONTAINER_DECLARE(CCCollection, HKHubArchBinaryNamedPort); \
CC_CONTAINER_DECLARE(CCCollection, HKHubArchProcessor);

#define CC_CONTAINER_DECLARE_PRESET_CCConcurrentBuffer()

#define CC_CONTAINER_DECLARE_PRESET_CCConcurrentIndexMap()

#define CC_CONTAINER_DECLARE_PRESET_CCConcurrentQueue()

#define CC_CONTAINER_DECLARE_PRESET_CCData()

#define CC_CONTAINER_DECLARE_PRESET_CCDictionary() \
CC_CONTAINER_DECLARE(CCDictionary, CCString, CFTypeRef); \
CC_CONTAINER_DECLARE(CCDictionary, CCString, GLShaderAttributeInfo); \
CC_CONTAINER_DECLARE(CCDictionary, CCString, GLShaderLibrarySource); \
CC_CONTAINER_DECLARE(CCDictionary, CCString, GLShaderUniformInfo); \
CC_CONTAINER_DECLARE(CCDictionary, CCString, HKHubModuleDisplayBufferConverter); \
CC_CONTAINER_DECLARE(CCDictionary, CCString, uint8_t); \
CC_CONTAINER_DECLARE(CCDictionary, HKHubArchPortID, HKHubArchPortConnection); \
CC_CONTAINER_DECLARE(CCDictionary, HKHubModuleWirelessTransceiverPacketSignature, uint8_t); \
CC_CONTAINER_DECLARE(CCDictionary, uint8_t, HKHubArchProcessorDebugBreakpoint); \
CC_CONTAINER_DECLARE(CCDictionary, uint8_t, size_t); \
CC_CONTAINER_DECLARE(CCDictionary, uint8_t, uintptr_t);

#define CC_CONTAINER_DECLARE_PRESET_CCHashMap()

#define CC_CONTAINER_DECLARE_PRESET_CCLinkedList() \
CC_CONTAINER_DECLARE(CCLinkedList, CCArray); \
CC_CONTAINER_DECLARE(CCLinkedList, HKHubArchExecutionGraphInstruction); \
CC_CONTAINER_DECLARE(CCLinkedList, HKHubArchProcessorInstructionGraphNode);

#define CC_CONTAINER_DECLARE_PRESET_CCList() \
CC_CONTAINER_DECLARE(CCList, uint64_t);

#define CC_CONTAINER_DECLARE_PRESET_CCOrderedCollection() \
CC_CONTAINER_DECLARE(CCOrderedCollection, CCComponent); \
CC_CONTAINER_DECLARE(CCOrderedCollection, CCExpression); \
CC_CONTAINER_DECLARE(CCOrderedCollection, CCString); \
CC_CONTAINER_DECLARE(CCOrderedCollection, CCTextAttribute); \
CC_CONTAINER_DECLARE(CCOrderedCollection, CCTextDrawable); \
CC_CONTAINER_DECLARE(CCOrderedCollection, CC_CONTAINER(CCOrderedCollection, CCTextAttribute)); \
CC_CONTAINER_DECLARE(CCOrderedCollection, FSPath); \
CC_CONTAINER_DECLARE(CCOrderedCollection, FSPathComponent); \
CC_CONTAINER_DECLARE(CCOrderedCollection, HKHubArchAssemblyASTError); \
CC_CONTAINER_DECLARE(CCOrderedCollection, HKHubArchAssemblyASTNode); \
CC_CONTAINER_DECLARE(CCOrderedCollection, HKHubModuleWirelessTransceiverPacketSignature); \
CC_CONTAINER_DECLARE(CCOrderedCollection, _Bool); \
CC_CONTAINER_DECLARE(CCOrderedCollection, double); \
CC_CONTAINER_DECLARE(CCOrderedCollection, float);

#define CC_CONTAINER_DECLARE_PRESET_CCQueue() \
CC_CONTAINER_DECLARE(CCQueue, uint8_t);
